# Generated by Django 2.2.7 on 2020-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartguard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
    ]
